//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaitehallintaEntities2 : DbContext
    {
        public LaitehallintaEntities2()
            : base("name=LaitehallintaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Laitetyypit> Laitetyypit { get; set; }
        public virtual DbSet<Laitteet> Laitteet { get; set; }
        public virtual DbSet<Henkilot> Henkilot { get; set; }
        public virtual DbSet<Postinumerot> Postinumerot { get; set; }
        public virtual DbSet<Tapahtumalokit> Tapahtumalokit { get; set; }
        public virtual DbSet<Tapahtumatyyppit> Tapahtumatyyppit { get; set; }
        public virtual DbSet<Varastopaikat> Varastopaikat { get; set; }
        public virtual DbSet<Varastot> Varastot { get; set; }
    }
}
