//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laitteet
    {
        public System.Guid Laite_uid { get; set; }
        public Nullable<System.Guid> Laitetyyppi_uid { get; set; }
        public string Laitenimi { get; set; }
        public string Sarjanumero { get; set; }
        public string Merkki { get; set; }
        public string Malli { get; set; }
        public Nullable<System.DateTime> Hankitapaiva { get; set; }
        public string Muisti { get; set; }
        public string Kovalevynkoko { get; set; }
        public Nullable<System.Guid> Varastopaikka_uid { get; set; }
        public string Lisatietoja { get; set; }
    
        public virtual Laitetyypit Laitetyypit { get; set; }
    }
}
