//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laitetyypit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laitetyypit()
        {
            this.Laitteets = new HashSet<Laitteet>();
        }
    
        public System.Guid Laitetyyppi_uid { get; set; }
        public Nullable<int> Laitetyyppi { get; set; }
        public string Laitetyyppinimi { get; set; }
        public string Lisatietoja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laitteet> Laitteets { get; set; }
    }
}
