//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapahtumalokit
    {
        public System.Guid Tapahtumaloki_uid { get; set; }
        public Nullable<System.DateTime> Paivamaara { get; set; }
        public Nullable<System.Guid> Henkilo_uid { get; set; }
        public Nullable<System.Guid> Laite_uid { get; set; }
        public Nullable<System.Guid> Tapahtuma_uid { get; set; }
        public string Lisatietoja { get; set; }
    }
}
