//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapahtumatyyppit
    {
        public System.Guid Tapahtumatyyppi_uid { get; set; }
        public Nullable<int> Tapahtumatyyppi { get; set; }
        public string Tapahtumannimi { get; set; }
        public string Lisatietoja { get; set; }
    }
}
