//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varastopaikat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Varastopaikat()
        {
            this.Laitteet = new HashSet<Laitteet>();
        }
    
        public System.Guid Varastopaikka_uid { get; set; }
        public Nullable<System.Guid> Varasto_uid { get; set; }
        public string Varastopaikannimi { get; set; }
        public string Lisatietoja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laitteet> Laitteet { get; set; }
        public virtual Varastot Varastot { get; set; }
    }
}
