//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointcollegeLaitehallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varastot
    {
        public System.Guid Varasto_uid { get; set; }
        public string Varastonnimi { get; set; }
        public Nullable<System.Guid> Varastonsijainti_uid { get; set; }
        public string Lisatietoja { get; set; }
    }
}
